name: Deploy websites to Github Pages

on:
  push:
    branches:
      - next

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Print metadata
        run: |
          echo "Commit: ${{ github.sha }}"
          echo "Branch: ${{ github.ref_name }}"

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch tags if any
        run: |
          git fetch --unshallow --tags
          echo $?
          git tag --list

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: yarn || true

      - name: Build project
        run: |
          cd packages/docs
          yarn build

      - name: Configure git
        run: |
          git config --global user.email "noreply@github.com"
          git config --global user.name "GitHub"

      - name: Deploy docs
        run: |
          mkdir gh-pages
          cp -r packages/docs/build/* gh-pages/
          cd gh-pages
          git init
          git add .
          git commit -m "Deploy to GitHub Pages"
          git branch -M gh-pages
          git push -f https://x-access-token:${{ secrets.GH_PAGES_DEPLOY_PAT }}@github.com/${{ github.repository }} gh-pages
